package seng201.team0.gui;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import seng201.team0.models.Car;
import seng201.team0.services.GameEnvironment;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import java.io.IOException;

public class SetupScreen {
    @FXML private TextField username;
    @FXML private Slider raceAmount;
    @FXML private Label statSpeed;
    @FXML private Label statHandling;
    @FXML private Label statReliability;
    @FXML private Label statFuelEconomy;
    @FXML private Label statPrice;
    @FXML private Label balanceLabel;
    @FXML private Label purchasedCar1;
    @FXML private Label purchasedCar2;
    @FXML private Label purchasedCar3;

    private GameEnvironment game;
    private Car selectedCar;
    private Stage stage;

    //Loading The Setup Screen
    public void init(GameEnvironment game, Stage stage) {
        this.game = game;
        this.stage = stage;
        updateBalance();
    }
    private void updateBalance() {
        balanceLabel.setText("$" + game.getBalance());
    }



    //Difficulty
    @FXML
    public void onEasyPressed() {
        game.setDifficulty("Easy");
        updateBalance();
    }
    @FXML
    public void onHardPressed() {
        game.setDifficulty("Hard");
        updateBalance();
    }

    //Cars
    private void showCarStats(Car car) {
        selectedCar = car;
        statSpeed.setText("Speed: " + car.getSpeed());
        statHandling.setText("Handling: " + car.getHandling());
        statReliability.setText("Reliability: " + car.getReliability());
        statFuelEconomy.setText("Fuel Economy: " + car.getFuelEconomy());
        statPrice.setText("Price: $" + car.getCost());
    }
    private void markCarAsPurchased(Car car) {
        if (purchasedCar1.getText().equals("N/A")) {
            purchasedCar1.setText(car.getCarName());
        } else if (purchasedCar2.getText().equals("N/A")) {
            purchasedCar2.setText(car.getCarName());
        } else if (purchasedCar3.getText().equals("N/A")) {
            purchasedCar3.setText(car.getCarName());
        }
    }
    @FXML
    public void onCarOnePressed() {
        showCarStats(new Car("Falcon", 200, 80, 95, 400, 3500));
    }
    @FXML
    public void onCarTwoPressed() {
        showCarStats(new Car("Cheetah", 220, 70, 90, 350, 4000));
    }
    @FXML
    public void onCarThreePressed() {
        showCarStats(new Car("Rhino", 180, 90, 98, 300, 3000));
    }
    @FXML
    public void onCarFourPressed() {
        showCarStats(new Car("Panther", 210, 85, 92, 370, 3800));
    }
    @FXML
    public void onCarFivePressed() {
        showCarStats(new Car("Wasp", 190, 75, 88, 420, 3200));
    }
    @FXML
    public void onCarSixPressed() {
        showCarStats(new Car("Blizzard", 195, 82, 96, 390, 3600));
    }
    //Any car names in this project have been generated by ChatGPT
    @FXML
    public void onPurchasePressed() {
        if (selectedCar == null) {
            showAlert("No car selected.");
            return;
        }
        if (game.getOwnedCars().size() >= 3) {
            showAlert("You can only purchase up to 3 cars.");
            return;
        }
        if (!game.canPurchase(selectedCar)) {
            showAlert("Not enough balance to purchase this car.");
            return;
        }
        game.purchaseCar(selectedCar);
        markCarAsPurchased(selectedCar);
        updateBalance();

    }

    //Continue And Back Buttons
    @FXML
    public void onContinuePressed() throws IOException {
        String name = username.getText().trim();
        if (name.length() < 3 || name.length() > 15 || !name.matches("[a-zA-Z0-9 ]+")) {
            showAlert("Invalid name. Must be 3–15 letters, no special characters.");
            // ChatGPT was used to help write the above 2 lines of code
            return;
        }
        if (game.getOwnedCars().isEmpty()) {
            showAlert("You must purchase at least one car.");
            return;
        }

        game.setPlayerName(username.getText().trim());
        game.setSeasonLength((int) raceAmount.getValue());

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/shop.fxml"));
        Parent root = loader.load();
        ShopScreen controller = loader.getController();
        controller.init(game, stage);
        stage.setScene(new Scene(root));
    }
    @FXML
    public void onBackPressed() throws IOException {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/start_screen.fxml"));
        Parent root = loader.load();
        StartScreen controller = loader.getController();
        controller.init(stage, new GameEnvironment());
        stage.setScene(new Scene(root));
    }



    //Alert
    private void showAlert(String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle("Input Error");
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}